name    'puppet-tomcat'
version '0.1.0'
source 'git://github.com/curator/puppet-tomcat.git'
author 'preston.norvell@gettyimages.com'
license 'MIT'
summary 'Puppet module for Apache Tomcat'
description 'Puppet module for Apache Tomcat'
project_page 'https://github.com/curator/puppet-tomcat'
